/** Form field definitions for each implemented design module. */
import { ModuleKey } from '../state/store';
import { END_CONDITIONS } from '../engine/buckling';
import { BOLT_GRADES } from '../engine/bolts';
import { STEEL_GRADES } from '../engine/materials';

export interface FieldDef {
  key: string;
  label: string;
  unit?: string;
  tooltip?: string;
  type?: 'number' | 'text' | 'select' | 'checkbox';
  step?: number;
  options?: Array<{ value: string; label: string }>;
  group?: string;
  showIf?: string; // input key that must be truthy
  min?: number;
  max?: number;
}

export const MATERIAL_FIELDS: FieldDef[] = [
  {
    key: '__grade',
    label: 'Steel grade',
    type: 'select',
    group: 'Material (IS 800 Table 1)',
    tooltip: 'IS 800:2007 Table 1 — designation of steels',
    options: [...STEEL_GRADES.map((g) => ({ value: g.grade, label: g.label })), { value: 'Custom', label: 'Custom…' }],
  },
  {
    key: '__band',
    label: 'Thickness band',
    type: 'select',
    group: 'Material (IS 800 Table 1)',
    tooltip: 'Yield stress reduces with thickness (Table 1)',
    options: [
      { value: 't<=20', label: 't ≤ 20 mm' },
      { value: '20<t<=40', label: '20 < t ≤ 40 mm' },
      { value: 't>40', label: 't > 40 mm' },
    ],
  },
];

export const FIELDS: Partial<Record<ModuleKey, FieldDef[]>> = {
  tension: [
    { key: 'T_kN', label: 'Factored tension T', unit: 'kN', group: 'Loads', tooltip: 'Design tension as per the load combination (Cl. 6.1)', min: 0 },
    { key: 'useHoles', label: 'Bolt-hole deduction for net area', type: 'checkbox', group: 'Net section (Cl. 6.3)' },
    { key: 'nHoles', label: 'Number of holes in chain', group: 'Net section (Cl. 6.3)', showIf: 'useHoles' },
    { key: 'holeDia', label: 'Hole diameter', unit: 'mm', group: 'Net section (Cl. 6.3)', showIf: 'useHoles', tooltip: 'Hole ⌀ = bolt ⌀ + 2 mm (Cl. 10.2.2) for computing An' },
    { key: 'plateWidth', label: 'Plate width', unit: 'mm', group: 'Net section (Cl. 6.3)' },
    { key: 'plateThickness', label: 'Plate thickness', unit: 'mm', group: 'Net section (Cl. 6.3)' },
    { key: 'useShearLag', label: 'Shear-lag β (angles connected by one leg)', type: 'checkbox', group: 'Shear lag (Cl. 6.3.3)' },
    { key: 'w1', label: 'w1 — outstand of connected leg', unit: 'mm', group: 'Shear lag (Cl. 6.3.3)', showIf: 'useShearLag' },
    { key: 'w2', label: 'w2 — outstand of outstanding leg', unit: 'mm', group: 'Shear lag (Cl. 6.3.3)', showIf: 'useShearLag' },
    { key: 'lagT', label: 't — thickness of leg', unit: 'mm', group: 'Shear lag (Cl. 6.3.3)', showIf: 'useShearLag' },
    { key: 'Lc', label: 'Lc — end-connection length', unit: 'mm', group: 'Shear lag (Cl. 6.3.3)', showIf: 'useShearLag', tooltip: 'Distance between outermost fasteners / equivalent weld length' },
    { key: 'A1', label: 'A1 — net area of connected leg', unit: 'mm²', group: 'Shear lag (Cl. 6.3.3)', showIf: 'useShearLag' },
    { key: 'A2', label: 'A2 — gross area of outstanding leg', unit: 'mm²', group: 'Shear lag (Cl. 6.3.3)', showIf: 'useShearLag' },
    { key: 'useBlockShear', label: 'Block shear check', type: 'checkbox', group: 'Block shear (Cl. 6.4)' },
    { key: 'Avg', label: 'Avg — gross area in shear', unit: 'mm²', group: 'Block shear (Cl. 6.4)', showIf: 'useBlockShear' },
    { key: 'Avn', label: 'Avn — net area in shear', unit: 'mm²', group: 'Block shear (Cl. 6.4)', showIf: 'useBlockShear' },
    { key: 'Atg', label: 'Atg — gross area in tension', unit: 'mm²', group: 'Block shear (Cl. 6.4)', showIf: 'useBlockShear' },
    { key: 'Atn', label: 'Atn — net area in tension', unit: 'mm²', group: 'Block shear (Cl. 6.4)', showIf: 'useBlockShear' },
    { key: 'useLug', label: 'Lug angle connection', type: 'checkbox', group: 'Lug angle (Cl. 10.12)' },
    { key: 'lugArea', label: 'Lug angle area', unit: 'mm²', group: 'Lug angle (Cl. 10.12)', showIf: 'useLug' },
    { key: 'lugMemberType', label: 'Main member type', type: 'select', group: 'Lug angle (Cl. 10.12)', showIf: 'useLug', options: [{ value: 'angle', label: 'Angle' }, { value: 'channel', label: 'Channel' }] },
    { key: 'forceLeg_kN', label: 'Force in outstanding leg', unit: 'kN', group: 'Lug angle (Cl. 10.12)', showIf: 'useLug' },
    { key: 'capGusset_kN', label: 'Fastener capacity lug→gusset', unit: 'kN', group: 'Lug angle (Cl. 10.12)', showIf: 'useLug', tooltip: 'Angle: ≥ 1.2 × force in outstanding leg; channel: ≥ 1.1 ×' },
    { key: 'capMember_kN', label: 'Fastener capacity lug→member', unit: 'kN', group: 'Lug angle (Cl. 10.12)', showIf: 'useLug', tooltip: 'Angle: ≥ 1.4 × force in outstanding leg; channel: ≥ 1.2 ×' },
    { key: 'nBoltsLug', label: 'Bolts lug→gusset', group: 'Lug angle (Cl. 10.12)', showIf: 'useLug', tooltip: 'Minimum 2 bolts (or equivalent weld)' },
    { key: 'checkSlenderness', label: 'Slenderness check (Cl. 3.8)', type: 'checkbox', group: 'Serviceability' },
    { key: 'lambda', label: 'KL/r', group: 'Serviceability', showIf: 'checkSlenderness' },
    { key: 'slendernessLimit', label: 'Limit', group: 'Serviceability', showIf: 'checkSlenderness', tooltip: '400 (no reversal) / 180 (reversal) / 250 (wind & seismic)' },
  ],
  compression: [
    { key: 'P_kN', label: 'Factored compression P', unit: 'kN', group: 'Loads', min: 0 },
    { key: 'endZ', label: 'End condition z-z', type: 'select', group: 'Effective length (Table 3)', tooltip: 'IS 800:2007 Table 3 — recommended K values', options: END_CONDITIONS.map((e) => ({ value: e.key, label: `${e.label} (K = ${e.k})` })) },
    { key: 'endY', label: 'End condition y-y', type: 'select', group: 'Effective length (Table 3)', options: END_CONDITIONS.map((e) => ({ value: e.key, label: `${e.label} (K = ${e.k})` })) },
    { key: 'Lz', label: 'Actual length (z-z)', unit: 'mm', group: 'Effective length (Table 3)' },
    { key: 'Ly', label: 'Actual length (y-y)', unit: 'mm', group: 'Effective length (Table 3)' },
    { key: 'classZz', label: 'Buckling class z-z', type: 'select', group: 'Buckling class (Table 10)', tooltip: 'Auto = per Table 10; override for special cases', options: [{ value: 'auto', label: 'Auto (Table 10)' }, { value: 'a', label: 'a' }, { value: 'b', label: 'b' }, { value: 'c', label: 'c' }, { value: 'd', label: 'd' }] },
    { key: 'classYy', label: 'Buckling class y-y', type: 'select', group: 'Buckling class (Table 10)', options: [{ value: 'auto', label: 'Auto (Table 10)' }, { value: 'a', label: 'a' }, { value: 'b', label: 'b' }, { value: 'c', label: 'c' }, { value: 'd', label: 'd' }] },
    { key: 'builtUpMode', label: 'Built-up system', type: 'select', group: 'Built-up members', options: [{ value: 'none', label: 'None (single rolled section)' }, { value: 'lacing', label: 'Lacing (Cl. 7.4)' }, { value: 'batten', label: 'Battening (Cl. 7.5)' }] },
    { key: 'lacingSpacing', label: 'Lacing spacing', unit: 'mm', group: 'Lacing (Cl. 7.4)', showIf: '__lacing' },
    { key: 'lacingTheta', label: 'Lacing angle θ', unit: 'deg', group: 'Lacing (Cl. 7.4)', showIf: '__lacing', tooltip: '40°–70° with member axis (Cl. 7.4.3)', min: 0, max: 90 },
    { key: 'flatWidth', label: 'Flat width', unit: 'mm', group: 'Lacing (Cl. 7.4)', showIf: '__lacing' },
    { key: 'flatThickness', label: 'Flat thickness', unit: 'mm', group: 'Lacing (Cl. 7.4)', showIf: '__lacing' },
    { key: 'LcBar', label: 'Lc — bar length (between fasteners)', unit: 'mm', group: 'Lacing (Cl. 7.4)', showIf: '__lacing' },
    { key: 'nLacingPlanes', label: 'Lacing planes', type: 'select', group: 'Lacing (Cl. 7.4)', showIf: '__lacing', options: [{ value: '1', label: '1 (single system)' }, { value: '2', label: '2 (double system)' }] },
    { key: 'singleLacing', label: 'Single lacing (vs double/two-way)', type: 'checkbox', group: 'Lacing (Cl. 7.4)', showIf: '__lacing' },
    { key: 'connectionCap_kN', label: 'End connection capacity', unit: 'kN', group: 'Lacing (Cl. 7.4)', showIf: '__lacing' },
    { key: 'nPanels', label: 'Number of panels', group: 'Battens (Cl. 7.5)', showIf: '__batten' },
    { key: 'panelLength', label: 'Batten spacing', unit: 'mm', group: 'Battens (Cl. 7.5)', showIf: '__batten' },
    { key: 'battenWidth', label: 'Batten width', unit: 'mm', group: 'Battens (Cl. 7.5)', showIf: '__batten' },
    { key: 'battenThickness', label: 'Batten thickness', unit: 'mm', group: 'Battens (Cl. 7.5)', showIf: '__batten' },
    { key: 'nBattens', label: 'Battens per cross-section', group: 'Battens (Cl. 7.5)', showIf: '__batten' },
    { key: 'memberDepth', label: 'c — distance between component centroids', unit: 'mm', group: 'Battens (Cl. 7.5)', showIf: '__batten' },
  ],
  flexure: [
    { key: 'Mz_kNm', label: 'Design moment Mz', unit: 'kN·m', group: 'Loads' },
    { key: 'V_kN', label: 'Design shear V', unit: 'kN', group: 'Loads' },
    { key: 'laterallySupported', label: 'Compression flange laterally supported', type: 'checkbox', group: 'Lateral torsional buckling (Cl. 8.2.2)' },
    { key: 'LLT', label: 'LLT — distance between restraints', unit: 'mm', group: 'Lateral torsional buckling (Cl. 8.2.2)', showIf: '__unsupported' },
    { key: 'C1', label: 'C1 — moment gradient factor', group: 'Lateral torsional buckling (Cl. 8.2.2)', showIf: '__unsupported', tooltip: '1.0 UBM · 1.36 mid-span point load · 1.88 equal end moments' },
    { key: 'useWebBearing', label: 'Web bearing / buckling at a load point', type: 'checkbox', group: 'Web bearing (Cl. 8.7.4)' },
    { key: 'F_kN', label: 'Concentrated force / reaction F', unit: 'kN', group: 'Web bearing (Cl. 8.7.4)', showIf: 'useWebBearing' },
    { key: 'b1', label: 'b1 — stiff bearing length', unit: 'mm', group: 'Web bearing (Cl. 8.7.4)', showIf: 'useWebBearing' },
    { key: 'atEnd', label: 'At member end (single-side dispersion)', type: 'checkbox', group: 'Web bearing (Cl. 8.7.4)', showIf: 'useWebBearing' },
    { key: 'useDeflection', label: 'Deflection check', type: 'checkbox', group: 'Deflection (Cl. 5.6.1)' },
    { key: 'delta', label: 'Computed deflection δ', unit: 'mm', group: 'Deflection (Cl. 5.6.1)', showIf: 'useDeflection' },
    { key: 'span', label: 'Span', unit: 'mm', group: 'Deflection (Cl. 5.6.1)', showIf: 'useDeflection' },
    { key: 'limitRatio', label: 'Limit (span / n)', group: 'Deflection (Cl. 5.6.1)', showIf: 'useDeflection', tooltip: 'e.g. 300 for span/300' },
  ],
  combined: [
    { key: 'P_kN', label: 'Axial force P (+T / −C)', unit: 'kN', group: 'Design forces' },
    { key: 'Mz_kNm', label: 'Moment Mz (major)', unit: 'kN·m', group: 'Design forces' },
    { key: 'My_kNm', label: 'Moment My (minor)', unit: 'kN·m', group: 'Design forces' },
    { key: 'V_kN', label: 'Shear V', unit: 'kN', group: 'Design forces' },
    { key: 'Td_kN', label: 'Td — tensile strength', unit: 'kN', group: 'Member capacities', tooltip: 'From Module 2 (Cl. 6)' },
    { key: 'Pd_kN', label: 'Pd — compressive strength', unit: 'kN', group: 'Member capacities', tooltip: 'From Module 3 (Cl. 7)' },
    { key: 'Mdz_kNm', label: 'Mdz — moment capacity (major)', unit: 'kN·m', group: 'Member capacities', tooltip: 'From Module 4 (Cl. 8), incl. LTB if applicable' },
    { key: 'Mdy_kNm', label: 'Mdy — moment capacity (minor)', unit: 'kN·m', group: 'Member capacities' },
    { key: 'Vd_kN', label: 'Vd — shear capacity', unit: 'kN', group: 'Member capacities' },
    { key: 'useAmplification', label: 'Amplify moments (m = Cm/(1−P/Pcr))', type: 'checkbox', group: 'Stability (Cl. 9.3.1)' },
    { key: 'KLz', label: 'KL — effective length (for Pcr)', unit: 'mm', group: 'Stability (Cl. 9.3.1)', showIf: 'useAmplification' },
    { key: 'Cm', label: 'Cm — equivalent uniform moment factor', group: 'Stability (Cl. 9.3.1)', showIf: 'useAmplification' },
  ],
  bolts: [
    { key: 'boltGrade', label: 'Bolt grade', type: 'select', group: 'Bolt', options: BOLT_GRADES.map((g) => ({ value: g.grade, label: `${g.grade} (fyb ${g.fyb}, fub ${g.fub})` })) },
    { key: 'd', label: 'Bolt diameter d', unit: 'mm', group: 'Bolt' },
    { key: 'hsfg', label: 'HSFG (slip-resistant) bolt', type: 'checkbox', group: 'Bolt', tooltip: 'Cl. 10.4 — friction grip bolts' },
    { key: 'muF', label: 'μf — slip factor', group: 'Bolt', showIf: 'hsfg', tooltip: '0.2 (as-received) … 0.5 (blasted + roughened)' },
    { key: 'nFriction', label: 'ne — friction surfaces', group: 'Bolt', showIf: 'hsfg' },
    { key: 'largeHoles', label: 'Large holes (kh = 0.85)', type: 'checkbox', group: 'Bolt', showIf: 'hsfg' },
    { key: 'nBolts', label: 'Number of bolts', group: 'Geometry' },
    { key: 'pitch', label: 'Pitch p', unit: 'mm', group: 'Geometry', tooltip: '2.5d ≤ p ≤ min(32t, 300 mm) (Cl. 10.2)' },
    { key: 'gauge', label: 'Gauge g', unit: 'mm', group: 'Geometry' },
    { key: 'endDist', label: 'End distance e', unit: 'mm', group: 'Geometry', tooltip: '≥ 1.7d0 (sheared) / 1.5d0 (rolled, machine cut)' },
    { key: 'edgeDist', label: 'Edge distance', unit: 'mm', group: 'Geometry' },
    { key: 'shearedEdge', label: 'Sheared edge (1.7d0 rule)', type: 'checkbox', group: 'Geometry' },
    { key: 'nShearPlanes', label: 'Shear planes (total)', group: 'Plates' },
    { key: 'nThreadPlanes', label: 'Shear planes intercepting threads', group: 'Plates' },
    { key: 'thickness', label: 'Thickness of connected plate', unit: 'mm', group: 'Plates' },
    { key: 'shear_kN', label: 'Shear per bolt V', unit: 'kN', group: 'Loads' },
    { key: 'tension_kN', label: 'Tension per bolt T', unit: 'kN', group: 'Loads' },
    { key: 'usePrying', label: 'Prying action check (T-stub)', type: 'checkbox', group: 'Prying (T-stub)' },
    { key: 'plateTp', label: 'End-plate thickness tp', unit: 'mm', group: 'Prying (T-stub)', showIf: 'usePrying' },
    { key: 'pryingA', label: 'a — bolt to plate edge', unit: 'mm', group: 'Prying (T-stub)', showIf: 'usePrying' },
    { key: 'pryingB', label: 'b — bolt to T-stem face', unit: 'mm', group: 'Prying (T-stub)', showIf: 'usePrying' },
    { key: 'pryingP', label: 'p — tributary length', unit: 'mm', group: 'Prying (T-stub)', showIf: 'usePrying', tooltip: 'Yield-line tributary width per bolt' },
    { key: 'pryingFu', label: 'Plate fu', unit: 'MPa', group: 'Prying (T-stub)', showIf: 'usePrying' },
    { key: 'totalLoad_kN', label: 'Total factored load (bolt group)', unit: 'kN', group: 'Bolt group (FR-6.3)' },
    { key: 'eccentricity', label: 'Eccentricity e', unit: 'mm', group: 'Bolt group (FR-6.3)', tooltip: 'Cl. 10.3.7 — eccentric connections (elastic vector method)' },
  ],
  welds: [
    { key: 'weldType', label: 'Weld type', type: 'select', group: 'Weld', options: [{ value: 'fillet', label: 'Fillet weld' }, { value: 'butt-full', label: 'Butt weld (full penetration)' }, { value: 'butt-partial', label: 'Butt weld (partial penetration)' }] },
    { key: 'size', label: 'Weld size s', unit: 'mm', group: 'Weld', tooltip: 'Fillet: leg length; Butt: penetration' },
    { key: 'length', label: 'Effective length Lw', unit: 'mm', group: 'Weld' },
    { key: 'position', label: 'Welding position', type: 'select', group: 'Weld', options: [{ value: 'shop', label: 'Shop (γmw = 1.25)' }, { value: 'field', label: 'Field (γmw = 1.50)' }] },
    { key: 'weldFu', label: 'Electrode fu', unit: 'MPa', group: 'Weld', tooltip: 'E.g. 410 for E410 electrodes (matching grade)' },
    { key: 'partThickness', label: 'Thickness of thinner part', unit: 'mm', group: 'Weld', tooltip: 'Min/max size per Cl. 10.5.2' },
    { key: 'edgeRounded', label: 'Rounded edge (max size = t − 1.5)', type: 'checkbox', group: 'Weld' },
    { key: 'N_kN', label: 'Normal force N', unit: 'kN', group: 'Loads' },
    { key: 'Valong_kN', label: 'Shear along weld', unit: 'kN', group: 'Loads' },
    { key: 'Vacross_kN', label: 'Shear across weld', unit: 'kN', group: 'Loads' },
    { key: 'useCombined', label: 'Combined throat stresses (Cl. 10.5.9)', type: 'checkbox', group: 'Combined stresses' },
    { key: 'sigmaPerp', label: 'σ⊥ (⊥ to throat)', unit: 'MPa', group: 'Combined stresses', showIf: 'useCombined' },
    { key: 'tauPerp', label: 'τ⊥ (⊥ to weld axis)', unit: 'MPa', group: 'Combined stresses', showIf: 'useCombined' },
    { key: 'tauPar', label: 'τ∥ (along weld axis)', unit: 'MPa', group: 'Combined stresses', showIf: 'useCombined' },
    { key: 'useGroup', label: 'Eccentric weld group (Cl. 10.5.10)', type: 'checkbox', group: 'Weld group' },
    { key: 'groupH', label: 'Weld length (each vertical)', unit: 'mm', group: 'Weld group', showIf: 'useGroup' },
    { key: 'groupW', label: 'Weld spacing', unit: 'mm', group: 'Weld group', showIf: 'useGroup' },
    { key: 'groupVx_kN', label: 'Vx', unit: 'kN', group: 'Weld group', showIf: 'useGroup' },
    { key: 'groupVy_kN', label: 'Vy', unit: 'kN', group: 'Weld group', showIf: 'useGroup' },
    { key: 'groupM_kNm', label: 'In-plane moment M', unit: 'kN·m', group: 'Weld group', showIf: 'useGroup' },
  ],
  serviceability: [
    { key: 'loadCase', label: 'Load case', type: 'select', group: 'Loading', options: [{ value: 'udl', label: 'Simply supported — UDL' }, { value: 'point', label: 'Simply supported — point load' }, { value: 'cantilever-udl', label: 'Cantilever — UDL' }, { value: 'cantilever-point', label: 'Cantilever — point load' }, { value: 'manual', label: 'Manual deflection entry' }] },
    { key: 'useManual', label: 'Enter deflection manually', type: 'checkbox', group: 'Loading' },
    { key: 'manualDelta', label: 'Deflection δ', unit: 'mm', group: 'Loading', showIf: 'useManual' },
    { key: 'span', label: 'Span / length', unit: 'mm', group: 'Loading' },
    { key: 'w_kNpm', label: 'UDL w', unit: 'kN/m', group: 'Loading' },
    { key: 'P_kN', label: 'Point load P', unit: 'kN', group: 'Loading' },
    { key: 'E', label: "E — Young's modulus", unit: 'MPa', group: 'Section & material' },
    { key: 'limitRatio', label: 'Total deflection limit (span/n)', group: 'Criteria (Cl. 5.6.1)', tooltip: '300 = span/300' },
    { key: 'deltaLive', label: 'Live-load deflection δLL', unit: 'mm', group: 'Criteria (Cl. 5.6.1)' },
    { key: 'limitRatioLive', label: 'Live deflection limit (span/n)', group: 'Criteria (Cl. 5.6.1)' },
  ],
};
